### ISSUE TITLE
Compatibility with cloudflare/workerd

### ISSUE THREAD

**Issue by MurmeltierS** [nullobsi/ftpdeno#10]
Hey there,

I used this repo as my starting point for implementing a Cloudflare Worker runtime compatible ftp client using [Cloudflares TCP Sockets API](https://developers.cloudflare.com/workers/runtime-apis/tcp-sockets), as there seems to be no public project (I'm aware of) trying to build this atm.

This worked surprisingly well and I'm thinking about releasing it as a package.

As my package would be mostly reliant on your exisitng codebase with some tweaks to replace Deno exclusive functionality, I wanted to reach out and ask if there is any intention on your end to make this project compatible with other environments and If you would prefer a contribution here over an independent new project.

That's all - thx for your time and this project.

**Comment by MurmeltierS** [comment]
I'll just drop this here for now: https://www.npmjs.com/package/workerd-ftp

**Comment by nullobsi** [comment]
Sorry for the late response, I've been busy. 

Anyway, that's perfectly fine.  Glad to see another implementation based on my work :)

If you make bug fixes to the internal logic, it would be much appreciated if they apply here to for it to be contributed. 

Thank you
