### ISSUE TITLE
SFTP with private key file based auth.

### ISSUE THREAD

**Issue by metarama** [nullobsi/ftpdeno#14]
How do I use this module connecting to an SFTP server that requiries private key file base authentication?

If enhancements to this module are required to accomplish the above use case what are the necessary changes?

**Comment by metarama** [comment]
Very likely you cannot implement SFTP given the current Deno limitations around node:crypto. See https://docs.deno.com/runtime/manual/node/compatibility#:~:text=node%3A-,crypto,%E2%84%B9%EF%B8%8F,-Missing%20Certificate%20class.

Nonetheless, please list the enhancements we need to support sftp.

**Comment by nullobsi** [comment]
Unfortunately SFTP is a completely different protocol to FTP and would be best served by a whole other library, since it needs SSH authentication and a different approach that serves FTP.
