### ISSUE TITLE
Need a simple example!

### ISSUE THREAD

**Issue by ghost** [nullobsi/ftpdeno#2]
Hi!
Please make a simple usage example!

**Comment by nullobsi** [comment]
I've added two usage examples in the `examples` folder. Though I suppose I should make a proper documentation for all of the exposed members on the `FTPClient` class. :)

**Comment by ghost** [comment]
thank you!
This is my mistake - I looked at https://deno.land/x/ftpc@v1.1.0 and there is no example but on https://github.com/nullobsi/ftpdeno  there is!
I closed issue
