### ISSUE TITLE
example bug

### ISSUE THREAD

**Issue by davidm-public** [nullobsi/ftpdeno#3]
seems like your example doesn't work as documented:

ie: This does not work:
```sh
import FTPClient from "https://deno.land/x/ftpc/mod.ts";
```

But this does work:
```sh
import {FTPClient} from "https://deno.land/x/ftpc/mod.ts";
```

**Comment by nullobsi** [comment]
oops haha- i changed the way it was exported so the documentation will work

ill fix it in a bit 🙂

**Comment by nullobsi** [comment]
i've updated the examples, thanks! :+1:
