### ISSUE TITLE
Throws on 125 response

### ISSUE THREAD

**Issue by sntran** [nullobsi/ftpdeno#9]
When starting a `downloadStream` command, a 125 response is received and thrown as error.

```
{
  code: 125,
  message: "Data connection already open; Transfer starting.",
  errors: []
}
```

Initial tracing shows that the FTPClient [expects a 150 response code](https://github.com/nullobsi/ftpdeno/blob/85cab4dc344af3b5d113f2dd511ac148522e7f1d/classes/FTPClient.ts#L265). However, since it already initialized the data connection, a 125 would be more appropriate here instead.

**Comment by nullobsi** [comment]
Hello, I just made a new release v2.1.1 that should solve this issue.

In addition, I've updated some of the APIs in v3.0.0 to use new Deno interfaces instead of the now deprecated Deno.writer and reader.

Thanks for doing the digging for me :)

**Comment by sntran** [comment]
Thank you! That was quick.

I did not even realize that there is a 3.0.0 release. Glad that you are moving forward with more web standards!

Not sure if this is the right place to suggest, but you can get away with `toArrayBuffer` and `toText` from `std` by wrapping the `ReadableStream` with `Response` and calling the appropriate function from there.

Can also re-implement `TextLineStream` I suppose. Your library can become dependency-free :D
